BEGIN;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Tapas_in_Sevilla.jpg?width=800' WHERE id = 3;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Julius_Frank_Maria_und_Josef_mit_dem_Jesusknaben.jpg?width=800' WHERE id = 4;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Belen_maya.jpg?width=800' WHERE id = 9;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Escape_Room_-_%22The_Expedition%22_%28Escape_Quest_Bethesda%29.jpg?width=800' WHERE id = 12;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/%E3%82%A4%E3%83%B3%E3%83%95%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%96%E3%83%AB%E3%83%BB%E3%82%BF%E3%82%A4%E3%83%97%E3%81%AE%E3%82%AB%E3%83%8C%E3%83%BC_%E5%B7%9D%E6%97%85%EF%BC%88%E3%83%AA%E3%83%90%E3%83%BC%E3%83%84%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%B0%EF%BC%89%E5%8A%A0%E5%8F%A4%E5%B7%9D%E7%B7%A8_%E3%82%A4%E3%83%B3%E3%83%95%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%96%E3%83%AB%E3%83%BB%E3%82%BF%E3%82%A4%E3%83%97P9170080.jpg?width=800' WHERE id = 13;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Escape_Room_-_%22The_Expedition%22_%28Escape_Quest_Bethesda%29.jpg?width=800' WHERE id = 16;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Jan_Steen_-_Skittles_Players_Outside_an_Inn.jpg?width=800' WHERE id = 17;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Cinderella_Castle_2013_Wade.jpg?width=800' WHERE id = 18;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Madrid_20.JPG?width=800' WHERE id = 20;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/EMILIO_BEAUCHY%2C_Caf%C3%A9_cantante%2C_hacia_1885%2C_copia_a_la_alb%C3%BAmina.jpg?width=800' WHERE id = 21;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Tapas_in_Sevilla.jpg?width=800' WHERE id = 22;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Paella_de_marisco_01_%28cropped%29_4.3.jpg?width=800' WHERE id = 24;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%9A%D0%BB%D0%B0%D1%81_60.jpg?width=800' WHERE id = 25;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Crash_pad.jpg?width=800' WHERE id = 26;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Yoga_at_a_gym.JPG?width=800' WHERE id = 27;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Tyrolean_crossing.ogv?width=800' WHERE id = 28;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/NAdo-JTF3.jpg?width=800' WHERE id = 29;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Sala_de_cine.jpg?width=800' WHERE id = 30;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Bernhardt_Hamlet.jpg?width=800' WHERE id = 33;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Quart_de_Poblet_-_Centre_Cultural_El_Casino_05.jpg?width=800' WHERE id = 36;
UPDATE planes SET imagen_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Cycling_%28road%29_pictogram.svg/langes-330px-Cycling_%28road%29_pictogram.svg.png' WHERE id = 38;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/LAquarium-Barcelona.jpg?width=800' WHERE id = 40;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Julius_Frank_Maria_und_Josef_mit_dem_Jesusknaben.jpg?width=800' WHERE id = 41;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Museu_Picasso_(Barcelona).jpg?width=800' WHERE id = 42;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Roller-skate.jpg?width=800' WHERE id = 46;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Senderismo-GR-11-Prineos.jpg?width=800' WHERE id = 47;
UPDATE planes SET imagen_url = 'https://commons.wikimedia.org/wiki/Special:FilePath/Blended_wing_aircraft.jpg?width=800' WHERE id = 48;
COMMIT;
SELECT id, nombre, substring(imagen_url, 1, 80) FROM planes WHERE id IN (3,4,9,12,13,17,18,21,24,25,27,29,30,33,36,38,42,46,47,48) ORDER BY id;
